---
title: "BioStat_2023_Homework 0"
output: word_document
date: "2023-09-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(flextable)
library(readxl)
library(openxlsx)
```


#Загружаем датасет

```{r}
read_delim("data_tsv.tsv") -> data0
```

```{r}
statistics <- list(
      `Количество субъектов` = ~length(.x),
      `Количество (есть данные)` = ~sum(!is.na(.x)),
      `Нет данных` = ~sum(is.na(.x)),
      `Ср. знач.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", mean(.x, na.rm = TRUE) %>% round(2) %>% as.numeric()),
      `Станд. отклон.` = ~ifelse(sum(!is.na(.x)) < 3, "Н/П*", sd(.x, na.rm = TRUE) %>% round(2) %>% as.numeric()),
      `95% ДИ для среднего` = ~sd(.x, na.rm = TRUE) %>% round(2) %>% as.numeric(),
      `мин. - макс.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(min(.x, na.rm = TRUE) %>% round(2), " - ", max(.x, na.rm = TRUE) %>% round(2)) %>% as.factor()),
      `Медиана` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", median(.x, na.rm = TRUE) %>% round(2) %>% as.numeric()),
      `Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(quantile(.x, 0.25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, 0.75, na.rm = TRUE) %>% round(2)) %>% as.factor())
)

data0 %>%
  select(c(`Группа`), where(is.numeric))  %>%
  group_by(`Группа`) %>%
  summarise(across(where(is.numeric), statistics)) %>%
  pivot_longer(!"Группа") %>%
  separate(name, into = c("Переменная", "Статистика"), sep = "_") %>%
  rename(`Значение` = value) %>%
  flextable() %>%
  theme_box() %>%
  merge_v(c("Группа", "Переменная")) -> data1
  write_rds(data1, "BioStat_2023/output_table.rds")

```

```{r}
data0 %>%
  select(`Группа`, `Группа крови`, where(is.factor)) %>%
  mutate(`Группа крови` = `Группа крови` %>% as.character() %>% replace_na("Нет данных") %>% as.factor()) %>%
  count(`Группа`, `Группа крови`) %>%
  group_by(`Группа`) %>%
  mutate(`Процент по группе` = (n / sum(n)) %>% round(4) %>% `*`(100) %>% str_c("%")) %>%
  ungroup() %>% 
  mutate(`Процент по выборке` = (n / sum(n)) %>% round(4) %>% `*`(100) %>% str_c("%"))
``` 

